                 **____________Video Object Detection by Yolo4_______________**

#### Import the Required Dependencies

In [6]:
import cv2
import numpy as np

### Loading weights and configuration file for yolov4
1. **'modelConfiguration' specifies the configuration file (yolov4-tiny.cfg)** that contains the architecture of the model, including the number of layers, filters, and other parameters.
2. **'modelWeights' specifies the pre-trained weights file (yolov4-tiny.weights)** that contains the learned parameters of the model. 

In [7]:
#read the wieghts and cfg file openCv , readNet function automatically detects an origin framework of a 
#trained model(readNetFromCaffe, readNetFromTensorflow, readNetFromTorch, or readNetFromDarknet).
net = cv2.dnn.readNet(r"C:\Users\Madina Computers\Documents\object_detection\dnn_model\yolov4-tiny.weights",\
                      r"C:\Users\Madina Computers\Documents\object_detection\dnn_model\yolov4-tiny.cfg")
model = cv2.dnn_DetectionModel(net)
model.setInputParams(size = (320,320),scale = 1/255)


#### Read the file that contain the name of different classes(objects name)

In [8]:
classes = []
with open(r"C:\Users\Madina Computers\Documents\object_detection\dnn_model\classes.txt","r") as file_object:
    for class_name in file_object.readlines():
        class_name = class_name.strip()
        classes.append(class_name)
print(classes)


['person', 'bicycle', 'car', 'motorbike', 'aeroplane', 'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'sofa', 'pottedplant', 'bed', 'diningtable', 'toilet', 'tvmonitor', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush']


##### Read the video file and also set the dimension of video frame


In [9]:
cap = cv2.VideoCapture(r"C:\Users\Madina Computers\Documents\object_detection\video.mp4")
# setting the dimension
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)


False

#### Draw the bbox and file name on video's objects

In [10]:
#as long as frame in the model
while True:
    #get frames
    ret,frame = cap.read()
    #get the bbox etc
    (class_ids, scores, bboxes) = model.detect(frame)
    for class_id, score, bbox in zip(class_ids, scores, bboxes):
        (x, y, w, h) = bbox
        #blue bbox
        cv2.rectangle(frame,(x,y),(x + w,y + h),(200,10,50),3)
        class_name = classes[class_id]
        #blue text
        cv2.putText(frame, (class_name),(x,y-10),cv2.FONT_HERSHEY_PLAIN,2,(200,10,50),2)
        cv2.rectangle(frame,(x,y),(x+w,y+h),(200,10,50),3)
    print('classs',class_ids)
    print('scores',scores)
    print('bboxes',bboxes) 
    

    cv2.imshow("Frame",frame)    
    key = cv2.waitKey(10)
    
    if key == 27:
        break

cap.release()
cv2.destroyAllWindows()

classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()


classs [2]
scores [0.8327732]
bboxes [[377 182  41  30]]
classs [2]
scores [0.70725596]
bboxes [[380 185  40  29]]
classs [2]
scores [0.6367391]
bboxes [[382 188  43  27]]
classs [2]
scores [0.6752239]
bboxes [[388 188  41  27]]
classs [2]
scores [0.7141511]
bboxes [[391 188  41  29]]
classs [2 2]
scores [0.5636509 0.7487304]
bboxes [[393 188  40  30]
 [400 192  36  27]]
classs [2 2]
scores [0.5008073 0.836197 ]
bboxes [[394 189  41  30]
 [399 191  38  28]]
classs [2]
scores [0.92052853]
bboxes [[399 190  42  30]]
classs [2]
scores [0.85955435]
bboxes [[401 192  45  31]]
classs [2]
scores [0.76891154]
bboxes [[404 193  46  29]]
classs [2 2]
scores [0.68548435 0.74770695]
bboxes [[406 195  46  29]
 [410 198  45  29]]
classs [2]
scores [0.75331765]
bboxes [[411 199  48  31]]
classs [7]
scores [0.729012]
bboxes [[411 199  55  33]]
classs [7]
scores [0.61653453]
bboxes [[410 199  60  34]]
classs [2]
scores [0.69060755]
bboxes [[431 204  41  28]]
classs [2 2]
scores [0.5692557  0.78829336]


classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()
scores ()
bboxes ()
classs ()


classs [5 5]
scores [0.7605838  0.91061383]
bboxes [[323 159 147  88]
 [339 158 130  86]]
classs [5 5]
scores [0.9250197 0.9562262]
bboxes [[327 161 145  87]
 [342 161 133  87]]
classs [5 5]
scores [0.7496737  0.77373064]
bboxes [[328 159 148  88]
 [346 159 129  90]]
classs [5 5 5]
scores [0.87630206 0.70229805 0.7199081 ]
bboxes [[334 161 145  91]
 [346 162 132  90]
 [355 163 126  89]]
classs [5 5]
scores [0.6397258  0.58479375]
bboxes [[328 163 161  89]
 [354 163 130  91]]
classs [5 5]
scores [0.616938   0.61990535]
bboxes [[328 159 172  97]
 [353 163 137  91]]
classs [5 5 5]
scores [0.6129285 0.740294  0.7058362]
bboxes [[353 165 149  96]
 [353 164 143  91]
 [357 165 141  96]]
classs [5 5 5]
scores [0.7503146 0.6194806 0.8367549]
bboxes [[360 165 151 100]
 [352 160 156  98]
 [356 169 153  93]]
classs [5 5 5 5]
scores [0.5589515  0.93128425 0.5338577  0.8700952 ]
bboxes [[351 162 165  94]
 [364 168 153  94]
 [356 163 158  93]
 [361 168 152  95]]
classs [5 5 5]
scores [0.89493823 0.64

### conclusion: 
our pre trained yolo4 model working very well over traffic video to detact car trucks etc as shown above the output of video,their bbox ,class name, class id etc
